### ISSUE TITLE
Wrap streamlit by pyinstaller | No module named 'wx by Matplotlib

### ISSUE THREAD

**Issue by chiehpower** [chiehpower/Python_demonstration#1]
```
27504 INFO:   Matplotlib backend "WX": ignored
    No module named 'wx'
27723 INFO:   Matplotlib backend "WXAgg": ignored
    No module named 'wx'
27941 INFO:   Matplotlib backend "WXCairo": ignored
    No module named 'wx'
```

### reference:

https://stackoverflow.com/questions/8609666/python-importerror-no-module-named-wx

**Comment by chiehpower** [comment]
Tried:

```
sudo apt-get install python-wxtools
```

**Comment by chiehpower** [comment]
```
149546 INFO: Looking for eggs
149546 INFO: Python library not in binary dependencies. Doing additional searching...
149629 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
149691 INFO: Warnings written to /home/wrap_streamlit/build/run_streamlit/warn-run_streamlit.txt
150058 INFO: Graph cross-reference written to /home/wrap_streamlit/build/run_streamlit/xref-run_streamlit.html
150464 INFO: checking PYZ
150464 INFO: Building PYZ because PYZ-00.toc is non existent
150464 INFO: Building PYZ (ZlibArchive) /home/wrap_streamlit/build/run_streamlit/PYZ-00.pyz
153862 INFO: Building PYZ (ZlibArchive) /home/wrap_streamlit/build/run_streamlit/PYZ-00.pyz completed successfully.
153968 INFO: checking PKG
153968 INFO: Building PKG because PKG-00.toc is non existent
153968 INFO: Building PKG (CArchive) run_streamlit.pkg
1099176 INFO: Building PKG (CArchive) run_streamlit.pkg completed successfully.
1099469 INFO: Bootloader /usr/local/lib/python3.8/dist-packages/PyInstaller/bootloader/Linux-64bit-intel/run
1099469 INFO: checking EXE
1099469 INFO: Building EXE because EXE-00.toc is non existent
1099469 INFO: Building EXE from EXE-00.toc
1099480 INFO: Copying bootloader EXE to /home/wrap_streamlit/dist/run_streamlit
1099482 INFO: Appending PKG archive to ELF section in EXE
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/build_main.py", line 782, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/build_main.py", line 714, in build
    exec(code, spec_namespace)
  File "/home/wrap_streamlit/run_streamlit.spec", line 23, in <module>
    exe = EXE(pyz,
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/api.py", line 507, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/datastruct.py", line 155, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/api.py", line 685, in assemble
    retcode, stdout, stderr = exec_command_all(
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/compat.py", line 475, in exec_command_all
    out, err = proc.communicate(timeout=60)
  File "/usr/lib/python3.8/subprocess.py", line 1024, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1867, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.8/subprocess.py", line 1068, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '('objcopy', '--add-section', 'pydata=/home/wrap_streamlit/build/run_streamlit/run_streamlit.pkg', '/home/wrap_streamlit/dist/run_streamlit')' timed out after 60 seconds
```

If `pyinstaller` includes the streamlit, then it will encounter this issue.

**Comment by chiehpower** [comment]
# Try with nuitka
https://github.com/Nuitka/Nuitka#install-nuitka

**Comment by chiehpower** [comment]
```
root@10:/home/wrap_streamlit# python -m pip install nuitka
Requirement already satisfied: nuitka in /usr/local/lib/python3.8/dist-packages (0.6.18.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@10:/home/wrap_streamlit# python -m nuitka --version
0.6.18.4
Commercial: None
Python: 3.8.5 (default, Jan 27 2021, 15:41:15) 
Flavor: Debian Python
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu "20.04.1

root@10:/home/wrap_streamlit# python -m nuitka --standalone run_streamlit.py 
FATAL: Error, standalone mode on Linux requires 'patchelf' to be installed. Use 'apt/dnf/yum install patchelf' first.

root@10:/home/wrap_streamlit# apt install patchelf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  patchelf
0 upgraded, 1 newly installed, 0 to remove and 65 not upgraded.
Need to get 53.4 kB of archives.
After this operation, 153 kB of additional disk space will be used.
Get:1 http://free.nchc.org.tw/ubuntu focal/universe amd64 patchelf amd64 0.10-2build1 [53.4 kB]
Fetched 53.4 kB in 0s (819 kB/s)    
Selecting previously unselected package patchelf.
(Reading database ... 20951 files and directories currently installed.)
Preparing to unpack .../patchelf_0.10-2build1_amd64.deb ...
Unpacking patchelf (0.10-2build1) ...
Setting up patchelf (0.10-2build1) ...

root@10:/home/wrap_streamlit# python -m nuitka --standalone run_streamlit.py 
Nuitka-Options:INFO: Used command line options: --standalone run_streamlit.py
Nuitka-Options:INFO: Detected static libpython to exist, consider '--static-libpython=yes' for better performance, but errors may happen.
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.18.4' on Python '3.8' commercial None.
Nuitka-Plugins:WARNING: Use '--enable-plugin=multiprocessing' for: Multiprocessing workarounds for compiled code.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'curses' added '_curses'.                                                    
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.                                                    
Nuitka-Plugins:WARNING: Use '--enable-plugin=numpy' for: Numpy support for at least 'pandas'.                                                       
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy' added 'numpy.compat,numpy.lib,numpy.linalg,numpy.fft,numpy.polynomial,numpy.random,numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.bit_generator,numpy.random.mtrand,numpy.ctypeslib,numpy.ma,numpy.matrixlib'.

Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'cryptography' added '_cffi_backend'.                                        
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'bcrypt._bcrypt' added '_cffi_backend'.                                      
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib3' added 'urllib3._collections,urllib3.connection,urllib3.connectionpool,urllib3.contrib,urllib3.contrib.appengine,urllib3.exceptions,urllib3.fields,urllib3.filepost,urllib3.packages,urllib3.packages.six,urllib3.packages.ssl_match_hostname,urllib3.poolmanager,urllib3.request,urllib3.response,urllib3.util,urllib3.util.connection,urllib3.util.queue,urllib3.util.request,urllib3.util.response,urllib3.util.retry,urllib3.util.ssl_,urllib3.util.timeout,urllib3.util.url,urllib3.util.wait,urllib.error,urllib.parse,urllib.request,urllib.response'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pycparser.c_parser' added 'pycparser.yacctab,pycparser.lextab'.             
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'matplotlib.backends' added 'matplotlib.backends._backend_agg,matplotlib.backends._tkagg,matplotlib.backends.backend_tkagg,matplotlib.backends.backend_agg'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PIL._imagingtk' added 'PIL._tkinter_finder'.                                
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'matplotlib.backends.backend_webagg' added 'matplotlib.backends.backend_webagg_core,tornado'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'matplotlib.backends.backend_webagg_core' added 'matplotlib.backends.backend_webagg,tornado'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'matplotlib' added 'matplotlib.backend_managers,matplotlib.backend_bases,mpl_toolkits'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.packaging' added 'pkg_resources._vendor.packaging.version,pkg_resources._vendor.packaging.specifiers,pkg_resources._vendor.packaging.requirements'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources.extern' added 'pkg_resources._vendor.packaging,pkg_resources._vendor.pyparsing,pkg_resources._vendor.six,pkg_resources._vendor.appdirs'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'nacl._sodium' added '_cffi_backend'.                                        
Nuitka-Plugins:INFO: pyzmq: Implicit dependencies of module 'zmq.backend' added 'zmq.backend.cython'.                                               
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy._lib' added 'scipy._lib.messagestream'.                               
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.random' added 'numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.bit_generator,numpy.random.mtrand'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.core' added 'numpy.core._dtype_ctypes,numpy.core._multiarray_tests'.  
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.internals' added 'pandas._typing,pandas,pandas.core.arrays._mixins,pandas.core.internals.blocks'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas.core.window' added 'pandas._libs.window'.                            
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.tslibs.parsing' added 'datetime,pandas._libs.tslibs.offsets'.  
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.parsers' added 'pandas._typing'.                               
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.tslibs.tzconversion' added 'datetime'.                         
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.tslibs.timezones' added 'datetime'.                            
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.linalg' added 'scipy.linalg.cython_blas,scipy.linalg.cython_lapack'.  
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.sparse.csgraph' added 'scipy.sparse.csgraph._validation'.             
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.special' added 'scipy.special._ufuncs_cxx'.                           
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.spatial' added 'scipy.spatial.transform,scipy.spatial.transform._rotation_groups'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.spatial.transform' added 'scipy.spatial.transform._rotation_groups'.  
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.spatial.qhull' added 'numpy.typing'.                                  
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.tslibs.nattype' added 'datetime,pandas._libs.tslibs.period'.   
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.tslibs.period' added 'pandas._libs.tslibs.nattype,pandas._libs.tslibs.offsets,pandas._libs.tslibs.timestamps,pandas._typing'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.tslibs.timestamps' added 'datetime'.                           
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.stats._stats' added 'scipy.special.cython_special'.                   
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.stats._qmc_cy' added 'scipy._lib._util'.                              
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.stats._sobol' added 'scipy._lib._util,typing_extensions'.             
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.tslibs.dtypes' added 'enum,pandas._libs.tslibs.offsets'.       
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.tslibs.timedeltas' added 'datetime'.                           
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.tslibs.conversion' added 'datetime'.                           
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.arrays' added 'pandas._typing'.                                
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.tslibs.vectorized' added 'datetime,pandas._libs.tslibs.dtypes,pandas._libs.tslibs.offsets'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.tslib' added 'datetime'.                                       
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs.lib' added 'pandas._typing,enum'.                              
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs' added 'pandas._libs.tslibs.np_datetime,pandas._libs.tslibs.nattype,pandas._libs.tslibs.base'.
Nuitka-Plugins:WARNING: Use '--enable-plugin=torch' for: torch support.                                                                             
Nuitka:INFO: Completed Python level compilation and optimization.                                                                                                          
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                                                                               
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.                                                                 
Nuitka-Scons:INFO: Running gcc -o /home/wrap_streamlit/run_streamlit.dist/run_streamlit -fuse-linker-plugin -flto=8 -fpartial-inlining -freorder-functions -O2 -O2 -z noexecstack -s -Wl,-R,'$ORIGIN' -Wl,--disable-new-dtags -Wl,-b -Wl,binary -Wl,./__constants.bin -Wl,-b -Wl,elf64-x86-64 -Wl,-defsym -Wl,constant_bin_data=_binary_____constants_bin_start @"./@link_input.txt -L/usr/lib -ldl -lm -lpython3.8 took 1819.41 seconds
Nuitka-Scons:WARNING: You are not using ccache.                                                                                                                            
Nuitka-Plugins:INFO: data-files: Included data file 'certifi/cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: data-files: Included data dir 'jsonschema/schemas' with 37 files due to package data directory for 'jsonschema'.
Nuitka-Plugins:INFO: data-files: Included data dir 'pytz/zoneinfo' with 32 files due to package data directory for 'pytz'.
Nuitka:INFO: Keeping build directory 'run_streamlit.build'.
Nuitka:INFO: Successfully created 'run_streamlit.dist/run_streamlit'.
```
